### ISSUE TITLE
Add instructions for pre-release checklist

### ISSUE THREAD

**Issue by nitin710** [EmotiBit/EmotiBit_Docs#32]
## Description
Add a place to store instructions for a checklist to be completed before making FW and SW releases.

## Type of correction
- [ ] Addition to the documentation
- [ ] Permission Issue(Any page you do not have access to
- [ ] Content Problem
- [ ] Inappropriate content
- [ ] Outdated/Deprecated content

## Link
- Add Link to the page where the problem exits [here]()
